
logging:
  outputLevel: "debug"
  outputStderr: false

  filePath: "explorer.log"
  fileLevel: "debug"

# Chain network configuration
chain:
  displayName: "BEACON EXPLORER"

# HTTP Server configuration
server:
  host: "0.0.0.0" # Address to listen on
  port: "8080" # Port to listen on

frontend:
  enabled: true # Enable or disable to web frontend
  debug: true
  minimize: false # minimize html templates

  # Name of the site, displayed in the title tag
  siteName: "BEACON EXPLORER"
  siteSubtitle: ""
  siteDomain: ""
  # link to EL Explorer
  ethExplorerLink: ""

  # file or inventory url to load validator names from
  validatorNamesYaml: ""
  validatorNamesInventory: ""

beaconapi:
  # beacon node rpc endpoints
  endpoints:
    - name: "testchain"
      url: http://52.76.172.102:3500

  # local cache for page models
  localCacheSize: 100 # 100MB

  # remote cache for page models
  redisCacheAddr: ""
  redisCachePrefix: ""

executionapi:
  # execution node rpc endpoints
  endpoints:
    - name: "testchain"
      url: http://52.76.172.102:8545
  
  depositLogBatchSize: 1000

# indexer keeps track of the latest epochs in memory.
indexer:
  # max number of epochs to keep in memory
  inMemoryEpochs: 3

  # disable synchronizing historic data
  disableSynchronizer: false

  # reset synchronization state to this epoch on startup - only use to resync database, comment out afterwards
  #resyncFromEpoch: 0

  # force re-synchronization of epochs that are already present in DB - only use to fix missing data after schema upgrades
  #resyncForceUpdate: true

  # number of seconds to pause the synchronization between each epoch (don't overload CL client)
  syncEpochCooldown: 2

  # maximum number of parallel beacon state requests (might cause high memory usage)
  maxParallelValidatorSetRequests: 1

# database configuration
database:
  engine: "sqlite" # sqlite / pgsql

  # sqlite settings (only used if engine is sqlite)
  sqlite:
    file: "./explorer-db.sqlite"

  # pgsql settings (only used if engine is pgsql)
  pgsql:
    host: 172.19.206.46
    port: 5432
    user: test
    password: test
    name: ""
  pgsqlWriter: # optional separate writer connection (used for replication setups)
    host: ""
    port: 5432
    user: ""
    password: ""
    name: ""